hello:
  language: 0
laguage:
  prop:
    desc: Test Stringi
    hello-language: 0
    lang-map:
      turkish:
        desc: Turkish language
        index: 1
        name: tr
      xyz:
        desc: XYZ language
        index: 1
        name: x
    language:
      desc: Turkish language
      index: 1
      name: tr
    multiplier: 0.7
    str-list:
    - osman
    - ali
    - veli
management:
  endpoint:
    caches:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9090
